name: Deploy Backend
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_KNOWN_HOSTS: ${{ secrets.EC2_KNOWN_HOSTS }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 400 key.pem
          mkdir -p ~/.ssh
          echo "$EC2_KNOWN_HOSTS" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          echo "Testing SSH connection..."
          ssh -i key.pem -v $EC2_USER@$EC2_HOST "whoami && pwd"
          echo "Deploying files..."
          rsync -avz --delete -e "ssh -i key.pem" ./ $EC2_USER@$EC2_HOST:/test/backend
          echo "Restarting backend..."
          ssh -i key.pem $EC2_USER@$EC2_HOST "cd /test/backend && npm install && pm2 restart backend || pm2 start index.js --name backend"
